# Generated by Django 3.2.4 on 2021-09-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyeruser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.city'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='college',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='world.College'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.country'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.NormalUser'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='language',
            field=models.ManyToManyField(blank=True, to='world.Language'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='main_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_spec', to='blog.category'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='schools', to='world.School'),
        ),
        migrations.AddField(
            model_name='lawyeruser',
            name='specialty',
            field=models.ManyToManyField(blank=True, related_name='specialties', to='blog.Category'),
        ),
    ]
